import React from "react";

export const metadata = {
  title: 'Next App | About',
  description: 'Generated by create next app',
}

export default function about() {
  return (
    <section>
      <h1 className={"text-3xl"}>About</h1>
      <p>
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Facilis maiores
        mollitia nam delectus illum iste nemo autem obcaecati corporis,
        perspiciatis eos, quidem consectetur quam. In quos iure dignissimos
        adipisci autem molestiae mollitia quia voluptas enim. Aperiam omnis
        itaque ex culpa dolore, ipsam sequi! Laudantium, eos.
      </p>
    </section>
  );
}
