import TheFooter from '@/components/TheFooter'
import TheHeader from '@/components/TheHeader'
import { store } from '@/store/store'
import Provider from 'react-redux'
import './globals.css'
import ReduxProvider from '@/store/Provider'

export const metadata = {
  title: 'Next App | Home',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={'min-h-screen bg-black text-white flex flex-col'}>
        <TheHeader />
        <main className="p-3 grow container">
          <ReduxProvider>
            {children}
          </ReduxProvider>
        </main>
        <TheFooter />
      </body>
    </html>
  )
}
